const STORY_DATA = {
  "Day 1": {
    "title": "Bella's Wedding Day",
    "guide": "1. Bella刚举办了婚礼，但是她的好朋友RachaeI却未能到场，来看看Bella是如何在邮件中向Rachael描述婚礼场景的吧。2. 试着将描述婚礼场地的句子标出来吧。",
    "en": "Hi Rachael, How're you doing? I hope you're feeling better. I cant say thank you enough for the wedding present you gave Freddy and me. This pair of antique vases is so pretty! The colour is unusual and gorgeous. We have put the vases on the chest of drawers in our living room—they perfectly match the rug and cushions. It was such a pity that you couldn't attend our marriage ceremony! All of our childhood friends were there. Anyway, I sorted some of the best pictures once we got back from the honeymoon, so you wouldn't miss this special occasion even though you were not able to show up. Neither of us was into a grand wedding. We just wanted it to be cosy, casual but meanwhile surrounded by an atmosphere of romance. Do you remember the small church with a bell tower which is located in the North District? I fell in love with the appearance of the venue the moment I saw it. It was also where my grandparents got married, so we didn't even hesitate to rent it. The location is great and the view is lovely. They also have a nice cottage that sleeps six. As you can see in the photos, at the entrance, there was a welcome board with our names on it. All the seats were decorated with ribbons and flowers. My hand­ held bouquet（手捧花束）was made of roses and tulips, which have the meaning of love. Have you noticed the blue earrings under my curly hair? It was you who mentioned that there should be usomething blue” at the wedding. The wedding went on well. My worst nightmare of a stranger breaking in and stopping the ceremony didn't happen—just kidding ! By the way, my twin nephew and niece are the cutest page boy and flower girl ever! Really hope you enjoy these photos. Have you moved into your new flat? Can't wait to hear from you !",
    "cn": "参考译斗你还好吗？我希望你感觉好些了。我真不知道要怎样感谢你送给我变失和弗雷迪的结婚礼物。这对古董花瓶太美了！颜色独特又华丽。我们已经把花瓶放在客厅的五斗柜上了---和我们的地毯和坐垫简直是绝配。你没能参加我们的结婚典礼真是太遗憾了！我们所有的儿时朋友都到场了。不管怎样，我一度完蜜月回来就整理出了最棒的照片，这样哪怕你没能到场，也不会错过这个特殊的时刻。我们都对盛大的婚礼不感兴趣，只希望它能够舒适随意但同时也有着浪漫的氛围。你记得那座位于北区、有一个钟楼的小教堂吗？我第一次看到那个场地时就爱上了它的外观。那里也是我祖父母结婚的地方，所以我们毫不犹豫地租下了它。那里位置绝佳，景色优美，还有一个能住六人的漂亮小屋。正如你在照片中看到的，入口处有一块写着我们名字的欢迎牌。所有的座椅都用缎带和花朵做了装饰。我的手捧花束是用玫瑰和郁金香做成的，它们都有爱的寓意。你注意到我卷发下的蓝色耳环了吗？你提过婚礼上应该有“蓝色的东西”。婚礼进行得非常顺利。我最糟糕的噩梦------个陌生人闯进来中止仪式—并没有发生，这只是开玩笑！顺便提一下，我的双胞胎侄子和侄女是最可爱的花童！真希望你会喜欢这些照片。你搬进你的新公寓了吗？我迫不及待地想收到你的回信！爱你的，贝拉"
  },
  "Day 2": {
    "title": "Rachael's New Flat",
    "guide": "1. Rachael给Bella回复了邮件，来看看她是如何介绍她的新公寓的吧。2. 试着标记出Rachael在搬进新公寓之前做了哪些工作吧。",
    "en": "Hey Bella, Thanks so much for sending me these wedding pictures! You're the most beautiful bride I've ever known—no kidding! Freddy also looked handsome. I love the photo in which he kissed your cheek by the fountain. My best mate , I wish I were there to witness your happiness! It was so unfortunate that I missed your big day because I fell off the ladder and broke my leg. However, my leg is definitely mending , so you needn't worry about me. About my flat, I got the key two months ago. Although it's a bit stressful to pay off the house loan, I'm super excited about having my own property! I was tired of living with flatmates. I'm so happy that I don't have to bear the noise of kids or wait to take a bath. The apartment block is well situated and the neighbourhood is nice and quiet. The nearest tube station is only a ten-minute walk and the railway line is also not far away. My flat is on the fifth floor and the view outside the window is great. There's a small balcony where I can look up at the sky or have a drink with my friends occasionally. I have many things to do before moving in. I changed the locks, checked the smoke alarms , covered the ground with dust sheets 5 got a dustbin 5 changed the bulbs and repaired a leaking pipe. However, all electrical appliances such as the water heater, microwave, freezer, dishwasher and kettle are included, and the air conditioning and central heating also work well, so I can save a lot. To be honest, decorating my own flat makes me think about how our parents bear the load of bringing up a family—ifs never easy. Anyway, my flat is still messy and dusty. I will invite you to come after tidying up!",
    "cn": "太感谢你发给我这些婚礼照片了！你是我所知道的最美丽的新娘—绝不是开玩笑！弗雷迪看起来也很帅气。我喜欢那张他在喷泉旁边亲吻你脸颊的照片。我最好的朋友，我多么希望自己能在现场见证你的幸福时刻啊！由于从梯子上掉下来摔断腿而错过你的重要日子，实在是太令人遗憾了。不管怎么说，我的腿显然已经好转了，所以你不用担心我。说到我的公寓，我两个月前拿到了钥匙。虽然还房贷会带来一点儿压力，但是能够拥有自己的房产实在是太让我开心了。我厌倦了和室友住在一起。我很开心可以不用再忍受孩子们的吵闹声，也不用等很久才能洗澡了。我的公寓楼位置很好，附近一带安静漂亮。最近的地铁站步行只需要十分钟，铁路也离这儿不远。我的公寓在六楼，窗外的景色很美。公寓有一个小阳台，我可以在那里仰望天空，也可以偶尔和朋友小酌一杯。在搬进去之前，我还有很多事情要做。我换了门锁，检查了烟雾报警器，给地面铺了防尘布，买了垃圾箱，换了电灯泡，还修了一根漏水的水管。但是所有电器，比如热水器、微波炉、冰箱、洗碗机和热水壶都包含在公寓之内，空调和中央供暖系统也都运转正常，所以我可以节省一大笔钱。说实话，装修自己的公寓让我认识到我们的父母是怎样负担起养家的责任的------点儿都不容易。不管怎样，我的公寓还很脏很乱，收拾干净后我会邀请你来的！最温暖的问候，蕾切尔"
  },
  "Day 3": {
    "title": "The Education System in the United Kingdom",
    "guide": "1. 英国教育素来以历史久、标准严、质量高闻名于世，下面跟随教育专家约翰逊先生了解一下英国的教育体系吧。2. 如果有不认识的单词，记得标记出来哦。",
    "en": "My name is Oliver Johnson, a qualified teacher in the UK and an education expert. I am very familiar with the British education system and I'd love to give you a basic introduction. British education is worldwide renowned （闻名的）for its high quality and standards. The law states that all children aged 5 to 16 must attend primary and secondary schools to have compulsive education. For children under 5, publicly- funded pre-schools are available. In primary schools, pupils are introduced to essential knowledge on subjects like the English language, including reading, grammar, punctuation and vocabulary, and others like Mathematics5 Science, History, Arts, PE, etc. The topics taught in classes cover world affairs, nature studies, the environment, and so on. At the end of this stage, students will be tested through National Curriculum assessments on core（核心的）subjects. From the age of 11 to 14, students receive their secondary-school education in British state or private schools. They study a broad range of subjects, such as the English language and literature, Arithmetic, Science （ Biology, Chemistry, Physics, etc. ） , Technology and Design, Engineering, Drama, Business and Economics, and more. Secondary school graduation covers the period from the age of 14 to 15. After 读故暮巧记PET核心词汇 the two-year study, students take GCSE （ General Certificate of Secondary Education） examinations. Afterwards it is upon their choice: they may either leave school or keep on studying at vocational colleges, or pursue higher education in a university. At the age of 16, following another two years of study, students may take A- Level exams or other exams required for university entry. Higher education begins with three-year undergraduate（本科）courses. On completion, students may also apply for postgraduate （研究生）programmes, either taught or research, and PhDs. Tuition fees may vary from universities and regions, but there're also many student grants they can apply for. Now, we will have a 15-minute break. Please don't forget to fill in the questionnaires we handed out before the lecture!",
    "cn": "我的名字是奥利弗•约翰逊，我是一名有资质的英国教师，也是一名教育专家。我对英国的教育体系非常熟悉，我很愿意给你们做一个基英国教育以高标准、严要求闻名于世。法律规定，所有5〜16岁的孩子都必须上小学和中学，接受义务教育。5岁以下的儿童可以去公费的托儿所。在小学阶段，学生们会接触各科目的基本知识，例如英语语言（包括阅读、语法、标点和词汇）以及其他科目，比如数学、科学、历史、美术、体育等。课堂中的教学主题会涵盖国际事务、自然研究和环境等。这一阶段的学习结束时，学生会参加国家课程评估考试，考查几门核心科目。11~14岁时，学生们在英国公立或私立学校接受中学教育。他们学习的科目范围非常广泛，比如英语语言和文学、算术、科学（生物、化学、物理等）、科技与设计、工程学、戏剧、商业与经济等。学生们通常在14~15岁时从中学毕业。在两年的学习之后，他们会参加GCSE（普通中等教育证书）考试。而接下来就是他们个人的选择了：他们可以离开学校，也可以选择在职业院校继续学习，或者是在大学里继续深造。16岁时，学生们再学习两年，可以参加A-Level考试或其他大学入学考试。高等教育以三年制的本科课程为开端。学生完成学业后，还可以申请教学型或研究型研究生课程，以本的介绍。及博士学位。学费会根据不同的大学和地区有所不同，但是也有很多可供学生申请的助学金。现在，我们休息15分钟。请不要忘记填写讲座开始之前我们分发下去的调查问卷！"
  },
  "Day 4": {
    "title": "Colourful School Life",
    "guide": "1, 小朋友，你最喜欢的课程是什么？你喜欢老师以怎样的方式授课呢？ 一起看看Judy小朋友在学校里的生活吧。2. 记得标记出新学到的单词和句式哦。",
    "en": "I am Judy, a fifth-grade primary school student in Beijing. I started my school life when I was 3 years old. In pre-school, I learned elementary survival abilities, such as communication and interpersonal skills. I had an easy time then. However5 after I entered primary school, I was under some stress. Some of the subjects were pretty hard, especially English. It was too difficult for me to recite the alphabet, distinguish the consonants and vowels, or pronounce words correctly, not to mention my bad handwriting. I was afraid of the ringing bell for English classes and even wanted to be absent. But my English teacher encouraged me and said, “ Every student is talented and has an equal chance to achieve success. If you learn to overcome challenges step by step, you can have great achievements. You should pay more attention in class and concentrate all your efforts on searching for the right solution to your problems.n I realised she offered me the exact method to solve my problem. In order to keep up with other students 5 I asked my parents to register for a tutorial English class for me and spent hours revising for my English exams. After a period of time, my English improved a lot and I could even hand in my examination papers earlier than others. Gradually, I could write English compositions or short essays. It was certain that my effort paid off! Even though English was once my weakness, doing scientific experiments in .该故事巧记PET核心词汇 the laboratory and solving maths problems have been my strong points. I have an obsession with numbers. In addition, I like outdoor classes very much, but they are sometimes cancelled because of bad weather. One day, we were taught about how to escape from a fire, but it began to rain suddenly. As a result, we had to go back to the classroom carefully and listened to the lecture with the topic Fire! Whose fault ? I believe many students don't like the teachers who always tell them, “ Please turn the book to Page 5. Today we'll learn Chapter 1 Unit 2...” and repeat whatever written in the books. I hope teachers can use some teaching methods to make the lessons more interesting. Would you like to share your experience at school?",
    "cn": "我叫朱迪，在北京的一所小学读五年级。我从3岁起就开始了我的学校生活。在学前班里，我学会了基本的生存能力，比如沟通技巧和交际技巧。我那时的生活很轻松。但当我进入小学后，就感受到了压力。有些科目真的很难，尤其是英语。对我来说，背诵字母表、辨别辅音和元音、正确地读单词真是太难了，我难看的书写就更不用提了。我害怕上英语课的铃声，甚至想逃课。但是我的英语老师鼓励了我，她告诉我：“每个学生都是有天赋的，都同样有可能取得成功。如果你学会了一步步克服困难，你就能取得优异的成绩。你应该在课堂上更专心地听讲，尽力找到解决你的问题的正确方法。”我认识到她给了我解决问题的正确方法。为了赶上其他同学，我让父母给我报了一个英语辅导班，并花了很多时间复习准备英语考试。一段时间之后，我的英语水平有了显著提高，我甚至可以比别人提前交卷。渐渐地，我可以写英语作文或者小论文了。我的努力确实得到了回报！虽然英语曾经是我的弱项，但在实验室里做科学实验和解数学题一直是我的强项。我对数字很痴迷。另外，我很喜欢上户外课，但是户外课有时会因为天气不好被取消。有一次，当我们正在学习如何从火灾中逃生时，突然下起了雨。结果，我们只能小心地回到教室，听一场主题为《火灾！谁的过错?》的讲座。我相信很多学生都不喜欢老师总是告诉他们：“请把书翻到第5页。今天我们学习第1"
  },
  "Day 5": {
    "title": "A Waiter Called Robin",
    "guide": "1. 小朋友，你喜欢去哪种餐厅吃饭呢？快看看下面这家新式餐厅是不是你喜欢的类型吧。2. 试着圈出Robin提到的食物哦。",
    "en": "\"Hello! I'm Robin. I'm here to introduce the new self-service restaurant. Just follow me!” uFirst, lefs go to the ' Vegetable Room'. This £ Monkeys5 Home * is made of potatoes and spinach； the 'Alice's Garden5 is made of broccoli, cabbages and tomatoes...Can you imagine they are just made of the common vegetables in our diet?” uThen we come to the £ Fresh Meat Room5. You can grill pork, lamb and chicken yourself. And all the chickens are fed corn. Sometimes we have salmon, tuna and big turkeys. Just pay attention to the noticeboard. Any questions?\" “Why can5t I find the chopsticks?” a tiny girl asked. \"Well. I will tell the boss about your request later. But I believe your friends can convince you to use the knife and fork. ” u Wow! The turkey is so delicious! Can you tell me any tricks? I am so interested in the recipea naughty boy asked suddenly. uSorry. Ifs still a secret for me.\" n Now, lefs go to the s Drink Room5. You can pick from these cans of soft drinks. They don't contain any alcohol. So just say ' Cheers!5 as adults do. You can also enjoy fresh pineapple, orange or peach juice. The clean cups and saucers are on the shelf. Remember to stir them and don't spill the drinks.\" 禳故事巧记PET核心词汇 参考译尊 “ It is not a good idea to miss meals and replace them with refreshments. But if you are too hungry to wait, help yourself to some coconut cookies or pies on the tables with a blue table-cloth.\" “ Finally, a warning for all of you. Please tell yourself c I have to watch my weight!5 before you want to eat too much. Your happiness is not far away. Let's enjoy a huge meal. One more thing, this is also a takeaway. You can order at home.” In fact, there are many “Robins” who will greet all the customers in this restaurant. They are smart robots and have similar voices. Surprised?",
    "cn": "“大家好！我是罗宾。接下来由我介绍这家新式自助餐厅。跟我来吧！”“首先，我们去'蔬菜房'。这道'猴子之家'是用土豆和菠菜制作而成的；这道'爱丽丝花园'是用西兰花、卷心菜和西红柿做成的……你能想象这些都是用我们日常饮食中常见的蔬菜做出来的吗？”“接下来我们来到的是'鲜肉房'。你们可以自己烤制猪肉、羊肉和鸡肉。所有的鸡都是用谷物喂养的。有时候我们还会有三文鱼、金枪鱼和大火鸡。记得关注我们的告示牌。大家有什么想问我的吗？”“为什么我找不到筷子呢？”有个小女孩问道。“哦。稍后我会把你的要求告诉老板。但我相信你的朋友们会说服你使用刀叉的。”“哇！这道火鸡太好吃了！你能告诉我一些窍门吗？我对这道菜的菜谱很感兴趣。”一个调皮的男孩突然问道。“抱歉，这对我而言还是一个秘密。”“现在我们去'饮料房你们可以从这些罐装的软饮料中挑选，它们都不含任何酒精，所以像大人们一样说'干杯！'吧。你们也可以享用新鲜的菠萝汁、橙汁或者桃汁。架子上有干净的杯子和茶碟。记得搅一搅，还有就是别把饮料给洒了。”“不吃正餐而改吃点心，这不是什么好主意。但如果你真的饿得等不及了，随意吃些椰蓉饼干或者馅饼，它们就放在铺有蓝色桌布的桌子上。”“最后，给你们所有人一个忠告。在你想吃很多食物之前，请告诉自己：'我要注意我的体重！'幸福就在不远处，让我们享用大餐吧！还有一件事，这也是一家外卖餐厅，你们可以在家点餐。”事实上，这家餐厅里有很多“罗宾”，它们会迎接所有的顾客。它们是智能机器人，声音都很相似。你们感到惊讶吗？Word1温0◎"
  },
  "Day 6": {
    "title": "The First Hamburger I Made",
    "guide": "1. 小朋友，你会自己做早餐吗？快来看看“我”为自己做了什么美味的早餐吧。2. 试着圈出“我”做早餐时用到了哪些食材吧。旻(heading)印)",
    "en": "Many children like tasty hamburgers and chips made in fast-food restaurants. But it's not for me. I don't like something sticky inside the roll. It tastes disgusting. I want to change the flavour myself and I believe I can make it, because I'm interested in the pots and pans in the kitchen and to be a cook is my dream. On a sunny morning, I got up early and prepared all the ingredients: eggs, flour, tomatoes, lettuces, cucumbers5 and raw beef. But I knew I failed the moment I took the bread out of the tin. I can hardly chew it. So I asked my mum to tell me what the problem was. With her help, the bread was ready 20 minutes later. Then I found a frying pan and used it to fry the beef. What a pity! I failed again. Because I got the same jar twice, I put too much spice. Immediately the kitchen was full of spicy smell. I covered my nose with a tissue. At that time all the objects such as cups and spoons were put everywhere. I wanted to give up. “ IVe poured you a cup of fruit juice. Grab it and then try again. You should give yourself plenty of time. And I will warn you if necessary,\" my mother said patiently. After a couple of minutes, the beef was ready. This time it was okay. At last, I cut up all the vegetables and put them between the bread. I bit into the hamburger I made. To be honest, it was acceptable, but no Day more. Anyhow, I finished my breakfast and learned many tips on how to cook. And in spite of the mess, I don't think I was wasting time or food. We should keep trying and asking. I felt absolutely terrific that day!",
    "cn": "很多孩子都喜欢快餐店里美味的汉堡和薯条。但我不一样，我不喜欢面包里那些黏乎乎的东西，那些尝起来很恶心。我想改变这种口味，而且我相信自己能做到，因为我喜欢厨房里的锅碗瓢盆，而且我的梦想是成为一名厨师。在一个晴朗的早晨，我很早就起来准备所有的原料：鸡蛋、面粉、西红柿、生菜、黄瓜和生牛肉。但当我把面包从烤盘中拿出来的那一刻，我就知道自己失败了。我几乎咬不动它。所以我让妈妈告诉我问题出在哪里。在她的帮助下，20分钟后面包做好了。然后我去找了一个平底煎锅，用它来煎牛肉。太遗憾了！我又失败了。由于我拿了同一个罐子两次，所以香料放多了。厨房里立刻充满了香料味。我用纸巾堵住了鼻子。那时，杯子、勺子之类的东西放得到处都是，我都想放弃了。“我给你倒了一杯果汁。赶紧喝，喝完再试一次。你应该给自己充足的时间。此外，如果有必要的话我会提醒你。”妈妈耐心地对我说。又过了几分钟，牛肉煎好了，这次还行。最后，我把所有的蔬菜切碎夹在了面包里。我咬了一口自己做的汉堡。说实话，汉堡还可以，但说不上很好。不管怎样，我做完了自己的早餐，而且学到了很多关于做饭的窍门。尽管杂乱不堪，但我并不觉得这是在浪费时间或者食物。我们应该不断尝试、多多提问。那天的感觉真是好极了！"
  },
  "Day 7": {
    "title": "A Present for My Mother",
    "guide": "1. 小朋友，你在母亲节时为妈妈准备过礼物吗？2. 记得标记出新学到的单词和句式哦。Reading）目））",
    "en": "Mother's Day is coming and I want to give my mother a special present. On Sunday when I walked on the street, I was attracted by an exciting advert on the wall, which was advertised as u Memories just for One\". And it showed all the goods were on sale in a shop. Ifs just on the opposite side of a supermarket where I often go shopping. Maybe it could give me a hint about my mother's present, so I decided to have a look there. Once walking in the shop, I was overwhelmed by shining brand new luxury goods like perfume, jewellery, and second-hand bags on the shelves. It was amazing, but everything seemed so dear. I complained that it seemed hard to find a present that I could afford. Just in time, an assistant came to help me. She told me to go to the women's section and maybe I could find something special but inexpensive for my mother. She was right. In the women's section, there were lots of pretty clothes like sleeveless dresses, jeans and well-made shoes on a shelf beneath. I soon found a special sweatshirt from many clothes. It was of good quality and the pattern of a mother holding a baby in her arms really attracted me. It was the obvious choice. But unfortunately, I didn't find a suitable size for my mother, which made me upset. I didn't want to give up, so I asked a shop assistant to see if there were other ways to get a suitable one. Luckily, she told me, “The sweatshirt you want is out of stock. We'll help you get the right size from other shops. But you need to wait at least three days and pay a deposit. If the item is not as satisfactory as you thought, we will exchange it or refund for you.” I was so happy to know that and thanked her a lot. I also chose a pair of knitting needles because it occurred to me that my mother likes to knit in her spare time. I came to the reception desk and asked, How much should I pay?” “Let me see. Your order has been reduced to £10 and as a student you can get a 50 percent discount.\" “ It means you only charge me half price. It's really a bargain.n I paid in cash and left. I hope my mother would be happy when she got my presents on Mother's Day.",
    "cn": "母亲节就要到了，我想送给妈妈一份特别的礼物。星期天，当我走在街上的时候，我被墙上的一则激动人心的广告吸引住了，上面写着“一个人的专属回忆”，并且显示店里的所有商品都在打折。这家店就在我经常去购物的超市对面。我决定去那里看看，说不定可以给我一些关于母亲节礼物的点子。刚走进商店，我就被里面闪闪发光的崭新奢侈品包围了，货架上有香水、珠宝，还有二手包。一切看起来棒极了，但所有的东西似乎都很贵。我抱怨说，要找到一件我买得起的礼物太难了。这时，刚好有位店员过来帮助我。她让我去女士专区看看，说不定能找到一些特别但又不贵的东西作为母亲节礼物。她说得没错。在女士专区，我找到了很多漂亮的衣服，比如无袖连衣裙、牛仔裤以及底层货架上制作精良的鞋。我很快就从众多衣服中找到了一件特别的运动衫。它的质量很好，而且上面的图案很吸引我—是一位母亲把婴儿抱在怀里。这显然是我想要的。但是很不巧，我没有找到适合我妈妈穿的尺码，这让我非常沮丧。我不想就这么放弃，所以决定去问问店员是否有别的办法可以买到合适的运动衫。幸运的是，她告诉我说：“你想要的这款运动衫已经脱销了。但我们可以帮你从别的商店调来尺码合适的。不过你至少要等三天，还得付订金。如果商品不像你想象的那样令人满意，我们可以给你换货或者退款。”听她这么说，我高兴极了。谢过店员之后，我又挑了一对毛衣针，因为我突然想起妈妈喜欢在空闲时间里织东西。我来到服务台询问：“我应该付多少钱?”“我来看看。打折之后你只用付10英镑，作为学生，你还可以享受五折优惠。”“也就是说你只收我半价。这真是太便宜了。”我付完现金就离开了。我希望妈妈在母亲节收到我的礼物时会艮开心。、Wordlist、0）advert['aedv3：t]。.广告同义advertisement广告搭配theadvertsontelevision电视广告advertise['sedvstaiz]/做广告;登广告何II句Trytoadvertiseandthentherewillbemorecustomers.尝试做做广告，这样就会有更多的顾客。"
  },
  "Day 8": {
    "title": "A “Green” Fashion Show",
    "guide": "1. 小朋友，你喜欢什么类型的衣服呢？你是否想过自己设计衣服呢？2. 试着找出“我们” 一起做了哪些衣服和饰品吧。",
    "en": "u Come on! Look at these. Do you still remember the styles we saw in the nearby shopping mall? We'd better finish the design one day ahead,H I told my classmates. My classmates and I were preparing for the u greenn fashion show competition at our school. That means we need to choose some materials from our daily life, such as paper, packets, plastic bottles, old clothes and so on. From this activity we can raise the awareness of recycling and protecting our environment. As a team, my classmates and I designed our logo together. Then, we decided to make a pullover with old clothes. After drawing different patterns, we cut and sewed them together. I drew our logo on the side of the sleeves. We also prepared a black tie which was made of silk. A pair of pants was made of old cotton shirts inside and plastic bags outside. We also made a hat with some newspapers and sewed two buttons on it. Besides, in order to make the hat unique, we wrote our names on its label. “Do you think they could be a good match without a pair of fashionable shoes?\" one of my classmates asked. Then I found a pair of sandals which I wore out last month and made some changes with plastic bottles. The shoes were not so tight as before and we gave the old sandals a new life. 该故享巧记PET核心词汇 Now we have an outfit for the “green” fashion show. I was chosen to be the model. I got undressed and tried on the outfit. A classmate fastened a ribbon around my neck and pinned a badge on the collar. Overall, they looked more stylish and fitted well. The next day I joined the long queue for the competition at our school. There were about 50 people, at a rough guess. But our design was obviously the most popular one because we got the highest score. I enjoyed the u green\" fashion show a lot and I hope we can make more people be aware of the importance of recycling.",
    "cn": "“来吧！看看这些。你们还记得我们在附近那家商场看过的款式吗？我们最好能提前一天完成设计。”我对同学们说。我和我的同学在为学校的一场“环保”时装秀比赛做准备。也就是说，我们需要从日常生活中选用一些材料，例如纸、盒子、塑料瓶、旧衣服等。通过这项活动，我们可以提高废物再利用以及保护环境的意识。作为一个团队，我和同学们首先一起设计了我们的队标。然后，我们决定用旧衣服做一件套头衫。在画完不同的图样之后，我们把它们裁剪下来再缝到一起。我在袖子的一侧画上了我们的队标。我们还准备了一条用丝绸做的黑领结。裤子里层是用旧棉布衬衫做的，外层是用塑料袋做的。我们还用报纸做了一顶帽子，上面缝了两颗扣子。此外，为了让这顶帽子显得独特，我们把自己的名字写在了它的标签上。“没有一双时尚的鞋，你们觉得这些衣服搭配起来会很好看吗？”一位同学问道。然后我就找出了一双上个月穿坏的凉鞋，以塑料瓶为原料对它做了一些改动。这双鞋不像之前那么紧了，我们让旧凉鞋变得焕然一新。现在我们有了一整套“环保”时装秀的服装。我被选为模特。我脱下身上的衣服去试穿这套衣服。一位同学在我的脖子上系了一根丝带，并且在我的衣领处别上了一枚徽章。总的来说，这套衣服看起来更时尚了，也很合身。第二天，我加入了学校比赛的长队，粗略估计有50人。我们的设计显然最受欢迎，因为我们队的得分最高。我很喜欢这场“环保”时装秀，我希望我们能让更多人意识到回收利用的重要性。"
  },
  "Day 9": {
    "title": "An Interesting Stamp Album",
    "guide": "1. 小朋友，你身边有爱好收集各种东西的人吗？你见过“智能邮票”吗？快来一探究竟吧！2. 记得标记新学到的单词和句式哦。",
    "en": "Last Sunday I was taken to see my grandparents. My grandfather is a big fan of technologies. I hid in the study to find his new secrets while they were busy preparing for the dinner. I looked round the study. Then a thick book with graphics on the desk interested me. I opened it carefully and pressed a button near a picture. A voice suddenly appeared. 11 Wow! What's that?\" I rushed to ask my grandfather. \"Oh, dear. Ifs my stamp album and ifs introducing the stamp's background/1 he answered with a laugh. “A new hobby? I've never heard you mention it!\" He told me that stamp collecting was a very popular hobby when he was young. He has been collecting stamps to kill his leisure time. Gradually blank pages of a stamp album were filled with a variety of stamps about historic figures and tourist attractions. These stamps remind him of the good memories. “In the past, thousands of people across the world had the habit of collecting stamps. However, with the development of society, kids these days generally have no interest in or dislike collecting items. The trend is probably that they are keen on science fiction and expedition in particular, so my students are doing experiments to develop J Smart Stamps5 and have published an article. The thoughts and results don't disappoint me. I expect to see further improvement in the future. Then maybe 尸f心词汇 more people will decide to be stamp collectors via a new technique. Do you fancy trying more modes? Let me tell you more details,\" he added. “Go on. It's fun. And can you take me to your laboratory next time? You hardly ever take me there. It must be a totally awesome experience.\" “I promise you. And you can share my photocopy with your classmates. Personally, stamps are an important part of our traditional culture. Therefore, they should be remembered forever,\" he explained. After dinner, I went home with the album photocopy and could not wait to show it to my classmates.",
    "cn": "上周日我被带去看望爷爷奶奶。我爷爷是一个科技迷。就在他们忙着准备晚饭的时候，我躲进了书房里寻找他的新秘密。我环视了一下书房。这时，桌上的一本有图片的厚书引起了我的兴趣。我小心地打开它，按下了一张图片旁边的按钮。突然，一个声音出现了。“哇！这是什么呀？”我赶紧跑去问爷爷。“哦，亲爱的。这是我的集邮册，它正在介绍这张邮票的背景。”他笑着回答道。“这是您的新爱好吗？以前从没听您提过！”爷爷告诉我，在他年轻时，集邮是很受欢迎的一种爱好。他一直通过集邮来消磨闲暇时光。渐渐地，一本集邮册的空白页就被各种关于历史人物、旅游景点的邮票填满了。这些邮票能带给他许多美好的回忆。“过去，世界各地成千上万的人都有集邮的习惯。然而，随着社会的发展，现在的孩子普遍对收集物品不感兴趣或者说不喜欢了。目前的趋势是他们特别热衷于科幻小说和探险,所以我的学生们正在做实验研发“智能邮票”，而且发表了一篇文章。这些想法和结果都没让我失望。我期待未来会有更多的进步，这样也许会有更多的人决定通过新技术手段成为集邮者。你想尝试更多的模式吗？我来跟你说一下更多的细节吧。”他补充道。“您说吧，很有意思。另外，您下次能带我去您的实验室吗？您还没带我去过呢。那肯定是一次非常棒的体验。”“我答应带你去。另外，你可以跟同学们分享我的集邮册复印件。在我看来，邮票是我们传统文化的重要组成部分，因此，它们应该永远被铭记。”他解释说。吃完晚餐后，我把这本集邮册复印件带回了家，迫不及待地想把它展示给同学们看。"
  },
  "Day 10": {
    "title": "My Father's New Novel",
    "guide": "1. 小朋友，你喜欢读小说吗？小说中的哪些情节最能吸引你呢？2. 试着用英语补全故事的结尾吧。",
    "en": "Besides working as a policeman, my father is a man of wide interests. He often goes hiking and swimming ； he even plans to go on a round-the-world cruise. However, what he likes most is to write novels. One day I went into his study whilst he was writing a new novel about a robbery. I used to be particularly uninterested in unreal stories because I didn't like to imagine things that were not really there, but he insisted that it was a true story that took place just months ago. This made me interested. \"Almost everything I wrote is true, though I may forget a few details. The story develops round five main characters. Two experienced thieves tried to steal an ancient sculpture at the art gallery. They hired a motorcycle first and then behaved like gentlemen, hanging out for quite a long time during the opening hours. There was not any action until midnight. What they didn't expect was that the police had been waiting outside and roped off the whole area. They also contacted the manager who was responsible for the security in advance. From the moment the thieves bought the tickets with a membership card, they were closely noticed. To everyone's disappointment, the policemen made a wrong decision when the thieves slid out, partly because it's impossible...\" He stopped suddenly and asked whether I was listening or not. “Don't tell me the ending part only exists in your head,” I responded. uYou're right! Just help me create something different. Let your imagination run wild and be creative. It wouldiTt :ake up too much of your time and will be of great importance for my writinghe continued. After days of reflection, I've got a general idea about the ending. But my dear reader, I wonder how you will finish the story as an . Maybe you can come up with a better idea than me. Please think it over and let me know.",
    "cn": "我爸爸除了当警察之外，还是一个兴趣很广泛的人。他经常去远足和游泳，甚至还计划乘船周游世界。然而他最喜欢的还是写小说。有一天，当我走进他的书房时，他正在写一部关于盗窃的新小说。我之前对虚构的故事特别不感兴趣，因为我不喜欢想象不存在的事情，但他坚持说那是一个就发生在几个月之前的真实故事。这引起了我的兴趣。“我写的故事几乎都是真实的，不过我可能忘了一些细节。故事是围绕五个主要人物展开的。其中两名经验丰富的小偷想偷走美术馆里的一尊古老雕像。他们先是租了一辆摩托车，然后表现得像绅士一样，在美术馆营业时间内闲逛了好长时间。他们在午夜之前都没有任何行动。他们没想到其实警察一直就在外面等着，而且把整片区域都用绳子围起来了。警察还提前联系了负责安保的经理。从这两个小偷用会员卡买票的那一刻开始，他们就被密切注意了。令人失望的是，当小偷溜出来时，警察做了一个错误的决定，部分原因是不可能……”他突然停了下来，然后问我是否还在听。“别告诉我故事的结尾还在您的头脑中！”我回应道。“没错！你帮我创作一点不一样的东西吧。让你的想象自由驰骋、发挥创意吧。这不会占用你太多时间，而这对我的写作而言意义重大。”他继续说道。想了几天之后，我已经对故事结尾有了一个大体的想法。但是，亲爱的读者，我更想知道如果你是作者，你会如何完成这个故事呢？也许你可以想出比我更好的点子。请认真想一想，然后告诉我吧。"
  },
  "Day 11": {
    "title": "The Power of Friendship",
    "guide": "1. 小朋友，你有像Laura —样的好朋友吗？他/她会在你面临困难时安慰和鼓励你吗？2. 试着标记表现“我”的心理变化的单词吧。",
    "en": "Laura is a beautiful and intelligent girl in my class and she is generous in giving help to everyone. Both of us are very fond of ballet, so we signed up for the ballet classes. At first, we were just ordinary friends. But something changed on Ballet Exam Days. I was really nervous and anxious during the exam, so I failed the first test. This disappointing result made me feel embarrassed and I was not very hopeful about the next exam. I refused to complete my assignments, and my attitude made my parents annoyed. \"I want to give up. I find myself unable to keep going 5n I couldn't help telling Laura. Then I quickly covered my face with my hands to prevent my tears from dropping onto the floor in the ballet rehearsal room （排练室）. She looked very surprised and said, “Are you serious? It sounds crazy. I think you need more time to consider it. If you give up now, you'll only regret it.” She hugged me and added, “Don't look so miserable! Don't be so negative.\" She calmed me down and what really comforted me was the gift she prepared for me. It was a pair of ballet shoes and a letter. I opened her letter and it read: \"You do have some difficulties now, but they are nothing compared to the graceful dancing. It is not realistic to perform well every time. Dancing well demands both time and skills. We should learn to be more confident by dancing. 巧记PET核心词汇 That's a wonderful personal experience! I'd be delighted to become your dancing partner. We should encourage each other. Come on!\" I felt very relaxed at that moment. And finally, I managed to pass the next exam. From then on, we always rehearse together. I am really looking forward to dancing with this reasonable, patient and reliable friend on the stage who gives me courage.",
    "cn": "劳拉是我们班上一个既漂亮又聪明的女孩，而且非常乐于助人。我们俩都很喜欢芭蕾舞，所以都报了芭蕾舞班。一开始我们只是普通朋友。但芭蕾舞考试的那些天发生了一些变化。考试期间，我太紧张焦虑，所以在第一场考试中考砸了。这个令人失望的结果让我感觉很难堪，同时我对下一场考试也不抱希望了。我拒绝完成我的任务，而我的态度惹怒了我的父母。“我想放弃。我发现自己坚持不下去了。”在芭蕾舞排练室里我忍不住告诉劳拉，然后快速地用双手遮住了脸，以免泪水落在地板上。她看起来很惊讶地说：“你是认真的吗？这听上去有些疯狂。我觉得你需要更多的时间去考虑。如果你现在放弃，将来会后悔。”她拥抱着我，补充道：“别一副闷闷不乐的样子！也别这么消极。”她尝试着让我冷静下来，更让我感到安慰的是她为我准备的礼物。那是一双芭蕾舞鞋和一封信。我打开她的信，上面写着：“你现在确实遇到了一些困难，但和优雅的舞蹈比起来，这根本算不了什么。每次都表演得很好是不现实的。把舞跳好需要时间和技巧。我们应该通过跳舞学会变得更自信。这种亲身经历是非常奇妙的！我很乐意成为你的舞伴。我们可以互相鼓励。加油！”那一刻我感到非常轻松。最终，我努力通过了随后的一场考试。从那以后，我和劳拉经常一起排练。我真的很期待与这位通情达理、充满耐心且值得信赖的朋友在舞台上共舞，是她给了我勇气。"
  },
  "Day 12": {
    "title": "A Stupid Mistake",
    "guide": "1. 小朋友，你在日常生活中犯过愚蠢的小错误吗？你从中学到了什么道理呢？2. 记得标记新学到的单词和句式哦。",
    "en": "Everybody makes mistakes, even extremely smart children! In fact, there is such a “genius” in my family who studies well but sometimes has no common sense at all — my elder brother, George. One day we were amazed to find a cute homeless cat on the balcony. But then we found it had eaten up our goldfish. We were much annoyed at it. Ifs so rude and cruel! After a while, the cat seemed to lose control and began to constantly shiver. Was the guilty cat seriously ill? We were confused about what to do. “Oh. It's the typical sign of a cold. Lefs give it some medicine for colds. Go ahead! ” my bossy brother ordered me. I gave him a challenging look but had no better choice. Then frightening things happened. We couldn,t wake the cat up. We sent it to the vefs at once and fortunately we arrived there in time. “I felt deeply ashamed of myself for doing the stupid decision. Please save it!” George begged and told the vet all the details. That was an embarrassing and suffering situation. We exchanged relieved glances until the vet gave a satisfied smile and the cat recovered. I must admit I was impressed by the gentle vet. At last, we were willing to take the cat home and take care of it. Now, this charming pet has attracted lots of our friends. Some friends are a bit jealous of me because we have such a cute cat. “ Does the cat feel depressed or bored at home? Will it be disappointed with its new owners?n I asked myself curiously. Anyhow, I hope the cat doesn't blame me or my brother for the mistake and I want it to be cheerful and full of energy all the time. OK, ifs time to end the story. You may think this is just an amusing story or a confusing experience or something enjoyable. However, I just want to inspire more people to protect animals in the right way and don't make mistakes carelessly.",
    "cn": "每个人都会犯错，即使是极其聪明的孩子。事实上，我家就有一个这样的“天才”，他学习很好，但有时连基本常识都没有—这个人就是我哥哥乔治。有一天，我们在阳台上意外地发现了一只可爱的流浪猫。但随后我们发现它吃掉了我们所有的金鱼，我们对此很恼火。这只猫太无礼、太残忍了！过了一会儿，这只猫似乎失去了控制，它开始不停地颤抖。这只心怀愧疚的猫是患重病了吗？我们彳艮困惑该做些什么。“哦，这是典型的感冒征兆。我们给它吃点感冒药。快！”我那爱指挥人的哥哥命令我说。我用不赞同的眼光看了他一眼，但也没有更好的选择。接下来可怕的事情发生了。我们叫不醒那只猫了。我们立刻把它送去了兽医诊所，幸好我们及时赶到了那里。“我为自己做出的愚蠢决定深感内疚。请救救它！”乔治一边恳求一边把所有细节告诉了兽医。那是令人尴尬且煎熬的场面。直到兽医露出满意的笑容、那只猫复原之后，我们才如释重负地看了看彼此。我必须承认我很佩服这位温柔的兽医。最后，我们心甘情愿地把猫带回了家并且照顾它。现在，这只惹人喜爱的猫吸引了我们的很多朋友。有些朋友还有点忌妒我们拥有如此可爱的猫呢。“这只猫在家会感到失落和无聊吗？它会对自己的新主人失望吗？”我好奇地问自己。不管怎样，我希望它不要责怪我和哥哥犯下的错误，我希望它一直开开心心、充满活力。好了，是时候结束这个故事了。你可能认为这只是一个搞笑的故事、一次让人莫名其妙的经历，或者是一件令人愉快的事。然而，我只是想鼓励更多人用正确的方式保护动物，不要因为粗心而犯错误。"
  },
  "Day 13": {
    "title": "A Digital Watch",
    "guide": "1. 小朋友，你平时主要通过什么方式来了解天气情况呢？电视？手机？还是…？2. 记得标记新学到的单词和句式哦。",
    "en": "I have a cousin who is still not used to living in London at present 5 though she has lived there for more than one year. She hates the humid climate in London. And she always complains about the unreliable weather forecast. The truth is the temperature may drop sharply and you can experience a mild or cool breeze and a freezing snowfall on the same day. I didn't hear from my cousin for a while and one day she asked for a video chat with me. “ Hey, have you ever heard about the digital watch? Since my job involves me travelling a lot and the weather always affects my daily plans, I need to know the weather conditions to help me make wise decisions. The advert says the digital watch can report exactly the weather conditions wherever I go or whenever I check it. That will be of great value to me,\" she glanced at the newspapers and said excitedly. uThat's cool! Tell me more about it,” I told her. She paused a second and continued, “The advert also introduces that notices will appear to inform users to take umbrellas and not to get wet or what they should wear when the watch senses the changes in weather. Apart from these functions, it can predict the time periods that will be sunny the next day so that people can enjoy the sunshine at ease. How nice !n \"Sounds great. It must be fairly expensive. But it deserves that high price,\" I responded. uActually, I called the number on the advert and I was told that the digital watch is on sale in the supermarket this weekend. If you buy two, you can have 50% discount. Are you interested in it?” She asked. 11 Absolutely! Count me in! I wish you told me earlier,\" I replied. “But I've been pretty busy lately and I have arranged an appointment with an extraordinary client this weekend. I attempted to ask for a leave but the client didn't approve of that. He asked nobody except me to meet him. Can you do me a favour and run errands（跑腿）for me?” she asked. \"No problem! I'll go and buy it this weekend,\" I said. Now I can't wait to have the digital watch.",
    "cn": "参考译尖我有一个表妹，到目前为止她仍然不习惯住在伦敦，尽管她已经在这里生活一年多了。她讨厌伦敦潮湿的气候。她还经常抱怨不靠谱的天气预报。事实就是，气温可能会骤降，你可以在同一天经历温和或凉爽的微风以及冰冷的降雪。我有一段时间没和表妹联系了，有一天她要求和我视频聊天。“嘿，你听说过智能手表吗？我因为工作经常到处跑，天气总是影响我的日常计划，所以我需要知道准确的天气状况来帮我做出明智的决定。广告上说，无论何时何地，智能手表都可以准确无误地报告天气情况。这对我而言很有价值。”她看了一眼报纸兴奋地说道。“这很酷！再给我具体讲讲。”我说。她停了一会儿，接着说：“广告上还介绍了当手表感知到天气变化时就会通知用户携带雨伞以防淋湿，或者应该穿什么。除了这些功能外，它还可以预测第二天的晴天时段，让人们放心地享受阳光。多方便啊！”“听起来很不错！这款手表一定很贵，但也值得。”我回答说。“事实上，我打了广告上的电话，他们告诉我这周末这款智能手表在商场有促销活动。买两件打五折。你有兴趣吗？”她问道。“当然！算我一个！你应该早点跟我说疽我回应道。“但我最近很忙，这周末要安排会见一位特殊的客户。我试过请假但客户没同意。他点"
  },
  "Day 14": {
    "title": "The Weather Must Be Crazy",
    "guide": "1. 小朋友，你曾经遇到过极端天气吗？2. 记得标记新学到的单词和句式哦。",
    "en": "Few things can make me so frightened as the extreme weather I dreamt on a windy night. The story goes like this. While my family were driving back home along a broad river, we got caught in a thunderstorm. It was blowing a gale and raining hard. The river rose to the height of the main road. I saw the yards nearby were all buried by mudslides（泥石 流）led by the thunderstorm within minutes. Our car crashed into a wall with a big hole on the windscreen. Standing in the icy water, we were absolutely frozen. The average temperature had dropped to approximately zero degrees centigrade. It was extremely difficult despite all our efforts to grasp something helpful. Whatever we did, we must be extra careful not to be pushed into the river. What chance was there of being alive? We were not sure. A sudden flash of lightning lit everything up for a second. Then we heard a loud voice from a big ship saying, \"The area has been declared a disaster zone. We urgently request the public to assist the people who are still alive.” We kept yelling for help and fortunately, we were given a bamboo by a man of medium height. We crawled forward inch by inch and finally got to the upper deck. Just as we were sailing forward with the maximum speed the storm really took off. A man slipped over and his leg started bleeding everywhere. I attempted to approach him 5 but failed in the end. I was completely exhausted. How I wished I could have wings and fly to save him. \"Wake up! You're late! ” my mother shouted. When I woke up, I found the sun shining as usual. What I dreamt really looked like a disaster movie. Luckily it was just in my dream, not the reality.",
    "cn": "没有什么事情像我在那个刮风之夜梦到的极端天气那样令我如此恐惧。故事是这样的。当我们全家人沿着一条宽阔的河流开车回家时，我们被雷雨困住了。狂风大作，大雨倾盆。河水暴涨，漫上了主路。就在几分钟之内，我看到附近的院子都被雷雨导致的泥石流淹没了。我们的车撞到了一面墙上，挡风玻璃上破了一个很大的洞。我们都站在冰冷刺骨的水里，冻僵了。平均温度已经降到了零度左右。尽管我们尽了最大的努力，但想要抓住一些有用的东西真的太难了。我们不管做什么都必须格外小心，以免被卷入河中。我们不确定自己还能不能活下去。突然，一道闪电在刹那间把一切照亮了。接着我们听到从一艘大船上传来了很大的声音：“该地区已被宣布为灾区。我们紧急要求公众协助幸存者。”我们不停地喊救命。幸运的是，一名中等身材的男子给了我们一根竹竿。我们一点一点地往前爬，最终到达了上层甲板。就在我们以最大航速前行时，暴风雨开始真正发力了。有位男士滑倒了，他腿上的血流得到处都是。我试着靠近他，但最后还是失败了。我真的筋疲力尽了。我真希望自己有双翅膀，飞过去救他。“快醒醒！你要迟到了！”妈妈在喊着。当我醒来后，我发现太阳依旧像往常一样照耀着。我的梦看起来就像灾难片一样。幸运的是，这一切只是发生在梦里，而不是在现实中。"
  },
  "Day 15": {
    "title": "Boss Day",
    "guide": "1. 小朋友，你想过长大后自己开公司吗？你想开什么样的公司呢？又会招聘什么样的员工呢？2. 记得标记新学到的单词和句式哦。^(Reading) Q)",
    "en": "I had never heard of any day named “ Boss Day\" before I came to a private school. One day, our teacher told us that on u Boss Day” some of us could be the employers, namely the \" bosses\", who were going to decide which candidates to employ, and the others would be the candidates who were going to apply for jobs. Every student was going to attend a job fair as either an employer or an employee. It was a great chance for students to practice job-searching skills. On Boss Day, our teacher prepared lots of application forms and contracts in case we were in need. I chose to be the employer. And I became the leader of a team. I still remember the feeling of sitting in front of the desk in the conference room talking about the conditions of employment to the candidates. Since I am a big fan of sci-fi and detective movies, I chose u SuperheroH as the name of my film company, First of all, I made a recruiting plan. I aimed to find a full-time director and several cameramen as the crew of the company. I hope they were at the very top of their professions. And the novelists who were good at writing sci-fi and detective novels were necessary, too. Moreover, I needed leading actors and actresses, and some part-time performers for various roles. These positions were really popular among the candidates. They talked about why they were the best choice during the interview and tried to grasp the possibilities to get the offer. Then I realised a good film crew also includes fashion designers, barbers, and hairdressers who were responsible for performers' costumes and haircuts, and a group of security guards for security issues. Besides, the teacher reminded me to employ an accountant, whose main duty was to do the accounts and deal with the tax issues, and a lawyer. In comparison, I found there were few people interested in these positions because they thought these jobs were tiring and there were always piles of work to do. At last, I decided to raise the salary to make these positions more attractive. Apart from the candidates' professional qualifications and experience, I also wanted them to be honest, easy-going and creative so that the team could have a good time together. Time passed quickly, and our recruitment was pretty successful. I received lots of applications and found some people I was looking for. I learned a lot from this u Boss Day” event and I couldn't wait to be a real boss one day.",
    "cn": "在上私立学校之前，我从未听说过“老板日”。有一天，老师告诉我们，在“老板日”我们可以选择成为老板去雇用求职者，或者成为求职者去找工作。每一位同学都将作为雇主或雇员参加招聘会。这是一个练习求职技能的好机会。在“老板日”这一天，老师准备了很多申请表和合同供我们使用。我选择成为一名老板，并且成了一个小组的组长。我依旧记得坐在会议室的办公桌前与应聘者谈论雇用条件的情景。由于热衷于科幻和侦探类电影，我给我们的电影公司取名为“超级英雄”。首先，我制订了一份招聘计划。我想寻找一位全职导演和几名摄影师作为公司的成员。我希望他们都是行业中的佼佼者。另外，擅长写科幻小说和侦探小说的小说家也是必不可少的。此外，我还需要男女主演和一些能兼职出演各种角色的演员。这些职位艮受求职者欢迎。他们在面试中努力证明自己是最合适的人选，抓住一切机会得到他们想要的工作。后来我意识到一个好的剧组还需要时装设计师、理发师和美发师来负责演员们的服装和发型，以及一组安保人员负责安全事宜。此外，老师还提醒我需要雇用一名负责记账和处理税务的会计以及一名律师。相比之下，我发现很少人对这些职位感兴趣，因为会计和律师通常有大量工作要做，会很累。最"
  },
  "Day 16": {
    "title": "A Policeman and His Diving Coach",
    "guide": "1. 小朋友，你对警察这个职业了解多少呢？其实，警察在危险的工作中也会遇到一些有趣的人或事，一起看看吧！2. 记得标记新学到的关于职业的单词哦。",
    "en": "Like most middle-aged policemen, my uncle is busy dealing with all kinds of cases: sending somebody who robbed a bank to prison or helping the elder people cheated by salesmen or saleswomen. He even helps unemployed criminals find jobs. When he was young, he wanted to be a diver, but gradually forgot about that. To my surprise, he recollected his diver dream in the line of duty recently. Two months ago, a customs officer called the police and reported that a crowd picked up a fight. One old bossy captain had been injured by the owner and employees of a seafood market. According to the owner's accurate description, the goods trade had been postponed three times and cost twice more than usual, which made the owner and employees unsatisfied and finally led to the fight. It was my kind uncle who looked after the old captain in hospital because the captain's two sons and daughter were all abroad. One of his sons was a banker and the other one was a judge. His daughter was a librarian. The captain has experienced a lot. When he was young, he was a professional diver. Then he turned to be a soldier and also once worked as a porter, a postman, a taxi driver and a famous baker in Australia. Several years ago, he quit the job of being a sailor and bought his fishing boat. Knowing the captain was going to retire soon, my uncle asked him to be his temporary diving coach. 参考译% Several weeks later, the news ran without legs. Everyone knew that my uncle started learning diving. Many friends of my uncle also wanted to join him. These friends came from different professions, such as architects, firefighters, scientists, lecturers, and professors. Among this group of friends, a firefighter and a vet made the rapidest progress, which made my uncle jealous. Now they are preparing a new diving programme and I heard some reporters from several publishers are going to interview them. “ I've never thought this 'selfish' captain could be our amazing diving coach. And I will do everything in my power to let him enjoy his wonderful retirement in China,” my uncle said. Why not? I think people can change as long as you treat or respect them sincerely.",
    "cn": "一名警官和他的潜水教练跟大多数中年警察一样，我叔叔每天忙着处理各种案件：把抢银行的人送进监狱；帮助被各种推销员欺骗的老人。他甚至还帮助失业的罪犯找工作。年轻时，叔叔曾经想做一名潜水员，但他逐渐放弃了。令我惊讶的是，最近他竟然能在执行公务之余重拾自己的潜水梦。两个月前，一名海关官员报警说发现了群体性斗殴。一名海鲜市场老板和他的员工把一名专横的老船长打伤了。根据市场老板的准确表述，货物交易被推迟了三次，要价却比平时高出了不止一倍，这使老板和员工不满，最终导致了斗殴。由于老船长的两个儿子和一个女儿都在国外，所以他住院期间都是我好心的叔叔在照顾他。他的一个儿子是亍家，另外一个儿子是法官。他的女儿是图书管理员。这名船长经历很丰富。年轻时，他是一名专业潜水员，后来他当了兵，也曾在澳大利亚当过搬运工、邮递员、出租车司机，还曾是一位很有名的烘焙师。几年前，他辞掉了水手的工作，买了一艘渔船。当得知船长很快就要退休后，我叔叔就请他做自己的临时潜水教练。几周后，我叔叔开始学潜水的消息不胫而走。他的很多朋友也想和他一起学。这些朋友来自各行各业，有建筑师、消防员、科学家、讲师和教授等。在这群朋友当中，有一名消防员和一名兽医学得最快，让我叔叔很羡慕。现在他们正在筹备一项新的潜水计划，而且我听说有几家出版机构的记者要来采访他们。“我从来没想过这个'自私的，船长能成为我们出色的潜水教练。我一定会尽全力让他在中国享受精彩的退休生活。”我叔叔说道。为什么不呢？我觉得人都是会变的，只要你真心地对待他们、尊重他们。"
  },
  "Day 17": {
    "title": "A Cool Surprise Party",
    "guide": "1. 小朋友，你崇拜的人是谁？他/她身上有哪些值得你学习的地方呢？2. 记得标记新学到的单词和句式哦。",
    "en": "Everyone has their own idol ； so do I. The idols may be celebrities in the music industry , the heroes or heroines in movies, or the authors of bestsellers. However, not everyone has the chance to meet their idols in real life. What I like most is a popular idol group. They dance quite well and have written many hit songs. I admire them not only because of their beautiful appearance but also because of their independent ideas, passion for their careers and hard work for clear goals. I always wanted to go to their concert, but I never made it because either my pocket money was not enough for the admission price or it was difficult to book the tickets. Last week, I tried one more time. Unfortunately, when I arrived at the ticket office, I was informed that all the concert tickets had been sold out and they wouldn't perform in the city where I live over a period of time. Since then I had been upset. And then I was taken to a \"Surprise Party” by my best friend yesterday. After I entered the room, I saw a big screen playing my idols * interview in a chat show and some scenes in which they were singing in a recording studio. Then, there was a concert video of them. The group were singing with guitarists and dancing with ballet dancers. At the end of the performance, I couldn't help but cheer and clap with the audience in the video. It was just like magic. “That's incredible! Did you do this for me?\" I screamed with excitement. uYes, it's entertainment only for you. In fact, I've been planning this for weeks. Anyhow, just enjoy your birthday party!n my friend looked shy and answered in a low voice. She was so nice and I couldn't thank her enough. Altogether it was a great surprise party for me. I hope my idols can be a major influence in my life and I will be as good as them in the future.",
    "cn": "每个人都有自己的偶像，我也一样。这些偶像可以是音乐界的名人、电影里的男女主角，也可以是畅销书作者。然而，并非每个人都有机会在现实生活中见到他们的偶像。我最喜欢的是一个流行偶像组合。她们舞跳得非常好，还创作了很多热门歌曲。我崇拜她们并不只是因为她们漂亮的外表，还因为她们独立的思想、对事业的热爱以及追求明确目标的努力。我一直想去看她们的演唱会，但不是因为零花钱不够买门票，就是因为太难订票而没去成。上周我又试了一次。不幸的是，当我到达售票处时，我被告知所有的票都卖完了，而且在接下来的一段时间里她们都不会再来我所在的城市演出了。从那时起，我就闷闷不乐。然而就在昨天，我最好的朋友带我参加了一个“惊喜派对”。我一进房间就看到超大的屏幕上播放着我的偶像们在一个访谈节目里的采访，以及她们在录音棚里唱歌的镜头。接着屏幕上开始播放她们的演唱会录像。她们随着吉他手的伴奏唱歌，与芭蕾舞者一起跳舞。表演结束后，我情不自禁地和屏幕上的观众一起为她们欢呼鼓掌。这一切就像变魔术一样。“真是难以置信！这是你为我准备的？”我兴奋地大叫着。“没错，这是专门为你准备的娱乐活动！事实上，我已经为这个准备了好几周。不管怎样，尽情享受你的生日派对吧。”我的朋友有点害羞，她轻声地回答着。她真是我最好的朋友，我对她有着说不出的感谢。总而言之，这对我来说是一次十分令人惊喜的派对。我希望我的偶像们能够对我的生活产生重大的影响，也希望自己将来可以像她们一样优秀。"
  },
  "Day 18": {
    "title": "A Silly Behaviour",
    "guide": "1. 小朋友，你在剧院或者其他娱乐场所遇到过突发状况吗？快来看看故事里“我”的经历吧！2. 记得标记新学到的单词和句式哦。",
    "en": "We should follow rules when entertaining ourselves. For example, we will not be admitted to the theatre after the performance has started ；. we will not be permitted to take photos if the valuable items are on permanent display ； we will not be allowed to let off fireworks in the forest. However, there are some people who always break the rules with silly behaviours, which may even cause big issues to the society. I met such a person at a theatre. It was during the interval of a new production of King Lear. The music stopped and the lights were turned up, The audience didn't stop chatting till there came a loud voice. u Attention, please! You can wear the headphones on your right side to listen to our podcast. There are five channels to choose! You can turn up or down the volume based on individual needs.n I tried the first channel. It was about the latest productions by the theatre: films, documentaries, TV series, soap operas, orchestra shows5 and concerts of folk music. Then I chose another one. Amazing! It was an interview of the performers from King Lear. They were talking about how many hours they rehearsed every single day. Indeed, it was a superb show which demanded much hard work. About ten minutes later, there was something wrong with my headphone. At 该故萼巧记PET核心词汇 参考译导 the same time, I smelt something burning. I looked around and found a man in the back row was smoking and a cigarette butt（烟头）was glowing red on the floor. I contacted security personnel immediately. With a strict inspection, they came to the conclusion that the wires underneath the carpet were turrit out due to the cigarette butt. This was the main reason why the complicated stereo system was out of order. But the man who smoked had not realised how incredibly stressed to the personnel and how dangerous to the other audience. A few days later, the news spread on social network platforms and received many reviews of criticism towards the man's silly behaviour. 愚蠢的行为",
    "cn": "我们在进行娱乐活动的时候应该遵守规则。比如，禁止演出开始后入场；禁止对永久展出的珍贵展品拍照；禁止在森林里燃放烟花爆竹。然而，总有一些人会用他们愚蠢的行为打破规则，并对社会造成很大的危害。我在剧院里就遇到过这样一个人。在新作《李尔王》的中场休息期间，所有音乐都停了，灯光也亮了起来。观众们交头接耳，直到广播中响起了一个洪亮的声音。“请注意！您可以戴上您右边的耳机来听我们的广播。有五个频道可供选择。您可以根据个人需求调节音量大小。”我试听了第一个频道。里面是剧院的新作介绍，有电影、纪录片、电视连续剧、肥皂剧、管弦乐队表演、民乐音乐会等。然后我选了另一个频道。太棒了！这是对《李尔王》表演者的采访。他们正在谈论每天要排练多长时间。的确，如此精彩的表演需要演员付出大量的努力。大约过了十分钟，我的耳机出现了故障。与此同时，我闻到了有东西烧焦的气味。我四处张望，发现后排有一名男子在吸烟，地上的烟头闪着红光。我立即联系了安保人员。经过仔细的检查，他们得出了结论：地毯下面的电线被烟头烧坏了。这也正是导致复杂的立体音响系统出现故障的主要原因。但吸烟的男子全然不知这件事令工作人员多么焦虑不安，同时也让其他观众陷入了怎样的危险之中。几天后，这则新闻被传到了社交网络平台，评论中满是对这名男子愚蠢行为的谴责。entertain[.ents'tem]z招待；使快乐；娱乐句Heentertainedusforhourswithhisjokes.他的笑话把我们逗乐了好几个小时。"
  },
  "Day 19": {
    "title": "The Journey to London",
    "guide": "1. 小朋友，你喜欢旅行吗？如果来一场异国之旅,你会选择去哪个国家呢？2. 试着将Mary游览过的景点用笔圈起来吧。",
    "en": "Mary was on holiday this week. She had been longing to travel abroad. After consideration, she chose London, the capital of England, as the tourist site. Before departure, she got her visa, packed her luggage, and learned about the local cultural custom in advance. After confirming the departure time and route, she took a cab to Beijing International Airport. She came to the check-in desk and got her boarding pass, boarded the plane on time by following the airport signposts5 and set off for London. After a 16-hour long-distance trip, the plane landed in London safely. On arrival at the airport, Mary took the underground to the hotel which was booked online. She checked in at the reception desk and put down her luggage. She would begin a wonderful journey in London. On the first two days, Mary decided to be a backpacker. She walked through the streets of London with a travel brochure to experience its culture and went to many famous places on foot, including Buckingham Palace, Big Ben, and The British Museum. She also bought a ticket at the booking office of the Royal Opera House and watched a great opera. On the third day, due to the long distance to the destination5 she chartered a car and had a self-driving tour. With slow speed, she enjoyed the magnificent landscape along the way, such as steep peaks, dense forests and long tunnels. 3 hours later, Mary reached a resort at the seaside where she had a wonderful time. During the trip, Mary lost her credit card and ID card. She almost couldrTt return home. Fortunately, she got help from the local embassy and found them. At the end of the journey, Mary went back by air after checkout and bought lots of souvenirs from duty-free shops for her family members and friends.",
    "cn": "玛丽本周休假。她一直想去国外旅行。考虑之后，她选择了英国首都—伦敦作为旅游地点。出发前，她办好了签证，收拾好了行李，并提前了解了当地的文化习俗。她确认出发时间与路线后，乘坐出租车前往北京国际机场。她在办理登机手续的服务台拿到了登机牌，然后根据机场指示牌准时登机，出发前往伦敦。经过16个小时的长途旅行后，飞机在伦敦安全着陆。一到机场，玛丽就乘坐地铁去了在网上预订的酒店。玛丽在前台办理完入住，放下了行李。她就要开始美好的伦敦之行了。在最初的两天，玛丽决定当一名背包客。她拿着一本旅行手册在伦敦街头穿行，感受这座城市的文化，还步行前往了当地的很多著名景点，如白金汉宫、大本钟和大英博物馆。她还在皇家歌剧院的售票处买了一张票，看了一场非常精彩的歌剧。第三天，由于目的地路途遥远，玛丽选择租车自驾旅游。她缓慢前行，欣赏了沿途的壮丽风景，如险峻的山峰、茂密的森林和长长的隧道。3个小时后，她到达了一处海边的度假胜地，在那里度过了美好的时光。旅行期间，玛丽遗失了她的信用卡和身份证，险些无法回国。幸运的是，她得到了当地使馆的帮助，找到了它们。旅程的最后，玛丽办理了退房，乘坐飞机回国，还从免税店给家人和朋友们买了很多纪念品。"
  },
  "Day 20": {
    "title": "Transport",
    "guide": "1. 各种各样的交通方式为我们的生活带来了极大的便利。小朋友，你能列举出哪些交通工具呢？2. 试着将文中提到的交通工具标记出来吧。",
    "en": "In ancient times, the means of transport is limited and time-consuming. When people went out, they could choose by horse on the land or to sail at sea. But now people can go to more places to visit and do business by air, by sea, by rail or by road with less time and energy. For the people who often go on business, it's really important to choose a convenient means of transport. If they travel overnight on a jet or train, they can buy the cabin for accommodations and enjoy thoughtful services on board. For the area that is heavily dependent on tourism 5 it's really important to have convenient airlines or routes. Only when the traffic facilities are improved can the tourist sites attract more people to visit. Transport makes the travel of goods possible. Goods are usually delivered via vans, lorries or rails within or out of the border, and they can also be carried through canals. The exchange of goods can not only provide supplies for people in different countries, but also promote the development of business and trade. In addition, vehicles need fuel to drive and the usage of fuel has also made great contributions to the development of our society. Transport makes people go far away to explore the world. Hitchhiking and backpacking make people on the way to experience the local culture. Sailing in the ocean makes lands connect and helps people go around the world. Enormous spaceships and rockets can send people to outer space to explore the endless universe. Traffic rules are important to keep transport in order. For pedestrians, when they are on the pavement, especially at the crossroads, they have to follow the traffic lights and road signs. For vehicles, ifs really dangerous when drivers take turnings, go backwards or brake, so they need to obey traffic rules and make their vehicles get in parking spaces reserved.",
    "cn": "在古代，交通运输手段有限，而且耗时。人们外出时，只能选择在陆地上骑马出行或者在海上航行。但是现在人们可以通过航空、航运、铁路或公路去更多的地方参观和做生意，而花费的时间和精力更少了。对于经常出差的人来说，选择一种便捷的交通方式很重要。如果需要在飞机或者火车上过夜，他们可以购买舱室住宿，并享受贴心的服务。对于高度依赖旅游业的地区来说，拥有便捷的航空公司或者航线是非常重要的。只有当交通设施得到完善时，旅游景点才能吸引更多的人前来参观。交通运输使货物的流动成为可能。境内外的货物运输通常通过货车、卡车或铁路来完成，也可以通过运河来运输。货物交换不仅能为不同国家的人们提供物资供给，还能促进商业和贸易的发展。此外，车辆需要燃料才能行驶，燃料的使用也为我们的社会发展做出了巨大的贡献。交通运输使人们可以走向远方探索世界。搭便车和背包旅行让人们得以在旅途中体验当地的文化。海洋航行使大陆联结，让人们能够环游世界。巨大的太空飞船和火箭可以将人类送入太空去探索无尽的宇宙。交通规则对于保持运输秩序来说非常重要。对于行人来说，在人行道上—尤其是在十字路口，他们必须看交通信号灯和路标。对于车辆来说，司机在转弯、倒车或刹车时真的很危险，因此他们必须遵守交通规则，同时要把车辆开进预留的停车位。"
  },
  "Day 21": {
    "title": "Approaching the Earth",
    "guide": "1. 我们生活的地球在宇宙中是独一无二的。地球上有很多可爱的生物，让我们一起看看吧。2. 如果有不认识的单词，记得标注出来哦。",
    "en": "Our universe has many planets, and the planet we are living on is the earth, which is covered by oceans and continents. How much do you know about this planet? Do you want to know more about it? Lefs approach and explore the earth together. Our earth has existed for hundreds of millions of years, and there are many marvellous sceneries formed during the period, such as dense rainforests on land, caves and stones in the mountains. Streams and rivers flow through valleys, and waterfalls fall down from cliffs. At the border of oceans, there are coasts covered by sands, which can make us feel relaxed when lying on the shore. Every day, we can see sunrise in the morning and sunset in the evening. All of these allow us to enjoy the beauty of nature. To live on this planet, food and water are important for humans. Farming is the foundation because crops grown on the farmland can provide food for us and solve the problem of hunger. Water is necessary for both plants and animals. Although the amount of sea water is large, freshwater resource is limited, and even worse 5 we are running out of it. Therefore, it is our duty to protect water resources on the earth and save water for next generations. Wildlife makes our natural world colourful, and there are giant animals like zebras and giraffes in Africa, kangaroos in Oceania, penguins in Antarctica and 哽故事巧记PET核心词汇 tiny creatures like mosquitoes in our world. However? more and more species are decreasing due to environmental destroy and human hunting. Many rare animals are killed, which has greatly damaged the ecological balance between humans and nature. Therefore, to protect our planet, we should get along well with other creatures on the earth.",
    "cn": "我们的宇宙中有许多行星，而我们生活的这颗行星叫作地球。地球的表面被海洋和大陆覆盖着。你对这颗行星了解多少呢？你是否想了解更多呢？让我们一起走近地球，探索其中的奥秘吧。我们的地球已经存在了数亿年，在此期间，形成了许多美妙的景观，如陆地上茂密的雨林、山峰中的山洞与岩石。溪流从峡谷中穿流而过，瀑布从悬崖上飞流而下。海洋的边界是被沙子覆盖的海岸，躺在沙滩上，我们会感到非常轻松。每天我们都可以看到清晨的日出和傍晚的夕阳。这些景色让我们享受到了自然之美。在这个星球上生存，食物和水对人类至关重要。农业是基础，因为农田里种植的农作物为我们提供食物并解决饥饿问题。水资源是动植物生存的必需品。尽管海水很多，但淡水资源却有限，更糟的是，我们的淡水资源正在逐渐消耗殆尽。因此，我们有责任为子孙后代节约用水，保护地球上的水资源。野生动物使我们的自然界丰富多彩，世界上有大型动物，如非洲的斑马和长颈鹿、大洋洲的袋鼠、南极洲的企鹅，也有蚊子之类的微小生物。但是，由于环境破坏和人类猎杀，越来越多的物种正在逐渐减少。许多稀有动物被猎杀，这极大地破坏了人与自然之间的生态平衡。因此，为了保护我们的星球，我们应该与地球上的其他生物和谐相处。"
  },
  "Day 22": {
    "title": "Lefs Go to the Farm",
    "guide": "1. 小朋友，你去过农场吗？你喜欢农场上的生活吗？快来看看格林一家在农场的有趣经历吧。2. 试着找出格林一家在农场经历了哪些事情吧。",
    "en": "The Greens live in the north of America. One day, Mr Green announced that the whole family would have a trip together during the vacation. But they hadn't decided where to go. At first, Mrs Green suggested going to Tampa Bay in Florida which is located in the southeast of the United States. She heard that the scenery there was very attractive 5 with navy blue sea and sky merging in one colour and waves beating the shore. However5 their children would like to go to see animals on Mr Green's uncle's farm. Several days ago, the old farmer just invited the family to visit his farm near the city, so they decided to drive directly to the farm which was to the northwest of their home and began their unbelievable trip to the countryside. On their way, they first passed through a region covered by bushes, and then drove by a river where they could hear the sound of frogs. The season was autumn, so the narrow path to Mr Green's uncle's farm was covered by leaves and branches. Shortly after they crossed a bridge, they came to the destination. The farm is peaceful because of the low population. It was full of lively animals like cattle, goats, donkeys and pigs on the farm. The whole family rather liked this place, because they had many interesting experiences here. For example, they learned how to take care of animals； they caught and observed ants together； they taught a parrot which was kept in a cage to repeat words together. They also had a nasty experience. Several bees attacked them, which almost ruined their good moods. Fortunately, they succeeded in defeating the bees with water and got on with their great trip. In the evening, the whole family lay on the grass and appreciated the sparkling stars in the sky. They spent the whole day there and even didn't feel tired and bored at all. The Greens had a quality family time on the farm.",
    "cn": "格林一家居住在美国北部O有一天，格林先生宣布全家将在假期进行一次旅行。但是，他们还没有决定去哪里。最初，格林夫人提议去位于美国东南部佛罗里达州的坦帕湾。她听说那里的景色非常迷人，蔚蓝色的大海与天空交融成一色，浪花拍打着海岸。但是，他们的孩子想去格林先生的叔叔的农场看动物。几天前，这位老农夫邀请格林一家去参观他在市郊的农场，因此他们决定直接开车前往位于自己家西北方向的农场，并由此开始了令人难忘的乡村之旅。在路途中，他们首先穿过了一片灌木区，然后驾车经过了一条河，河边可以听到青蛙鸣叫的声音。因为是秋季，通往农场的狭窄小路被树叶和树枝覆盖着。他们过桥后不久，便到达了目的地。由于人烟稀少，农场上十分宁静。农场上随处可见活泼的动物，如牛、山羊、驴和猪。格林一家都很喜欢这个地方，因为他们在这里经历了许多有趣的事情。例如，他们学会了如何照顾动物；他们一起捉蚂蚁来观察；他们一起教笼中的鹦鹉学说话。他们也有不好的经历。有几只蜜蜂袭击了他们，差点毁了他们的好心情。幸运的是，他们成功地用水击退了蜜蜂，继续他们美好的乡村之旅。晚上，全家人躺在草地上，欣赏夜空中闪闪发光的星星。他们在那里度过了整整一天，甚至没有感到一丝疲惫和无聊。格林一家在农场上度过了美好的家庭时光。announce[e'nauns]vc宣布例句Theywillannouncetheresultofthevotetonight.今晚他们将宣布投票结果。atfirst首先;最初例句Atfirsttheplacewasstrangetome.最初我对这个地方不熟悉。"
  },
  "Day 23": {
    "title": "Take Good Care of Your Body;",
    "guide": "1. 小朋友，你还记得自己最近一次生病的感受吗？来看一下Tom和Jessy的生病经历吧！2, 如果有不认识的单词，记得标注出来哟！",
    "en": "Tom likes to play sports. He often goes to the gym or exercises outside to strengthen his body and develop fitness. One day, when he was cycling, he fell down from the bike and hurt his ankles and knees. Unfortunately, his knees were injured severely and bled a lot. He was too painful to go to the hospital. Finally, with the help of some kind strangers, he was sent to the hospital in an ambulance. When he arrived at the hospital, the doctor first used bandages to stop his bleeding. After a careful check, Tom was told that his bone was injured and he had to take a small operation. After the operation 5 he had to sit in a wheelchair and take pills for3 months to recover. For a sport-loving boy, it is uncomfortable to stay at home and have such a long rest. After the injury, Tom pays more attention to safety when he does sports and learns to take good care of his body. Tom's sister Jessy has a weak body and often has illnesses because she hates workout. This time, she had a headache and couldn't stop coughing all day long. The next day, she began to have a fever and a sore throat. She felt ill and suffered a lot from the disease. Her mum decided to take her to the clinic and have a check. Jessy was told that she got a flu. The doctor gave her some aspirin and other pills according to the prescriptions. Several days later, she got better gradually. The experience makes Jessy realise the importance of workout. She decides to change her unhealthy lifestyle and take more exercise, such as jogging and yoga. She knows she needs to take good care of her body and keeps diseases away.",
    "cn": "汤姆喜欢运动。他经常去健身房或通过户外锻炼来强身健体。有一天，他骑自行车时从自行车上摔了下来，摔伤了脚踝和膝盖。不幸的是，他的膝盖受了重伤，流了很多血。巨大的疼痛让他无法去医院。最后，在一些好心陌生人的帮助下，他被一辆救护车送去了医院。当他到达医院后，医生首先用绷带给他止血。经过细致的检查，汤姆被告知他的骨头受伤了，他不得不做一个小手术。手术后，他得坐在轮椅上，并坚持服药3个月才能恢复。对于一个爱好运动的男孩来说，待在家里休息这么长时间，确实很不舒服。这次受伤后，汤姆在运动时更加注意安全了，并学会了照顾自己的身体。汤姆的姐姐杰西讨厌锻炼，所以身体虚弱，经常生病。这次，她头疼而且整天咳嗽。第二天，她开始发烧和嗓子疼。她很难受，这次生病让她很痛苦。她妈妈决定带她去诊所检查。杰西被告知她患了流感。医生按照处方给她开了一些阿司匹林和其他药。几天后，她逐渐好起来了。这次生病的经历让杰西意识到了锻炼的重要性。她决定改变自己不健康的生活方式，多做运动，例如慢跑和瑜伽。她知道她需要照顾好自己的身体，远离疾病。"
  },
  "Day 24": {
    "title": "Sports Count a Lot",
    "guide": "1, 小朋友，你喜欢运动吗？你最喜欢的运动是什么呢？跟大家分享一下你喜爱的运动吧！2. 遇到不熟悉的单词时，记得用笔标注出来哦。",
    "en": "Nowadays, people pay more and more attention to sports and health. For young people, they are fond of extreme sports, such as motor-racing and water skiing. High pitch and quick speed of motor-racing can make them excited. Water skiing is an exciting but dangerous sport. Beginners need to be trained by professional instructors, otherwise it may cause damage. Lifeguards are needed if there is an emergency. Boxing is another popular sport for the young to pursue excitement. For championship, competitors will compete and hit each other in a boxing ring. To protect themselves 5 they need to wear helmets, When competitors complete the matches, the audience will applaud enthusiastically for every competitor. Meanwhile, many young people are willing to join in all kinds of leagues, such as the squash league. They need to be patient when learning a new sport, because they have to experience many failures before acquiring it. Swimming is a popular water sport. Before getting into the water, swimmers will get changed in the changing room with their professional swimwear 5 which can make them swim faster in the race track. They also need skills, such as controlling their breaths well under water. Athletics can not only make us become quicker, higher and stronger, but also make our lives colourful. My uncle Bob, a former world high jump champion, told me that athletes need to have professional training with tracksuits every day. To obtain higher scores in the races, they have to make more efforts than others, so they are under great stress. After retirement, my uncle likes to watch track and field contests and various sports tournaments, such as horse-riding and ice hockey, to enrich his retired life.",
    "cn": "如今，人们越来越重视运动与健康。对于年轻人，他们喜欢极限运动，例如赛车和滑水。赛车可以产生很高的音量，并且速度很快，这会让他们感到兴奋。滑水是一项令人兴奋但危险的运动。初学者需要接受专业教练的培训，否则可能会造成伤害。如果发生紧急情况，需要救生员施救。拳击是年轻人追求刺激的另一种流行运动。为了获得冠军，拳击手在拳击台上互相攻击竞争。他们需要戴着头盔保护自己。比赛结束后，观众会为每一位选手热烈鼓掌。同时，许多年轻人愿意参加各种联赛，例如壁球联赛。学习一项新运动需要耐心，因为他们必须经历许多失败才能学会。游泳是一种流行的水上运动。在下水之前，游泳者会在更衣室里换上专业的泳衣，这可以让他们在赛道里游得更快。同时，他们还需要技巧，例如在水下控制好呼吸。田径运动不仅能让我们变得更快、更高、更强，还能让我们的生活丰富多彩。我的叔叔鲍勃曾经是世界跳高冠军。他曾告诉我，运动员们每天都需要穿上运动服接受专业的训练。为了在比赛中获得更高的分数，他们需要比别人付出更多的努力，因此他们承受着巨大的压力。退休后，叔叔喜欢观看田径比赛和各种体育锦标赛，例如骑马、冰上曲棍球，来丰富他的退休生活。extremesports极限运动"
  },
  "Day 25": {
    "title": "Our Environment Matters",
    "guide": "1. 小朋友，为了保护环境，你做过哪些事情呢？2. 在文中找一找我们经常面临的环境问题，以及我们应该采取的应对措施吧。",
    "en": "Our earth is crowded with exploded populations which have brought great burdens to the environment. Roads and streets are filled with cars, which are likely to cause traffic jams. A large amount of C02 emitted by people and cars has caused severe air pollution and damages the earth's atmosphere terribly, resulting in climate change and global warming. In addition, there is a sharp decrease in species and some rare plants and animals gradually disappear from our sight. These have thrown great challenges to us and are signals sent by nature, telling us that we should make the world go back on track. To protect our environment, we should take action. We ought to attach importance to the concept that different rubbish needs to be thrown into different rubbish bins. For instance, recycled rubbish like glass bottles should be put into a bottle bank for recycling. Nowadays, throwing rubbish away is prohibited in most places because of the damage it may cause to our surroundings. At the same time, advocating public transport can avoid traffic jams and reduce air pollution. Some environmental protection organisations aim to protect our earth by setting up rules for people. We also hope to find other efficient methods to make our earth a place in all kinds of species * favour to multiply and live. Our earth remains in a bad situation and none of us will survive if we carry on destroying it. Unfortunately, we have no option but to protect the earth. Everyone should take good care of the earth and make great efforts to overcome difficulties step by step, otherwise we may disappear from the earth one day like other species. 环境很重要",
    "cn": "我们的地球非常拥挤，人口爆炸式增长，给环境带来了沉重的负担。街道上到处是汽车，这很可能导致交通堵塞。人与汽车排放出大量二氧化碳，加重了空气污染，严重破坏了地球的大气层，进而导致气候变化和全球变暖。此外，物种急剧减少，一些稀有动植物逐渐灭绝，从我们的视野中消失。这些给人类带来了巨大的挑战，它们是自然界发出的信号，正告诫我们应该使世界回到正轨。为了保护环境，我们应该采取行动。我们应该重视垃圾分类的理念。例如，应将可回收垃圾（如玻璃瓶）放入回收站进行再利用。现在，大多数地方都禁止扔垃圾，因为这可能会对环境造成破坏。同时，倡导公共交通既可以避免交通拥堵，又可以减少空气污染。一些环保组织通过为人们制定规则来保护地球。我们也希望找到其他有效的方法，让我们的地球成为有利于各物种繁衍和生存的地方。地球的状况依旧十分糟糕，如果我们继续破坏地球，谁也无法生存。不幸的是，我们别无选择，只能保护人类赖以生存的地球。每个人都应该为保护地球做出努力，一步步克服困难，否则有一天，我们也会像其他物种一样从地球上消失。"
  },
  "Day 26": {
    "title": "Rubbish Sorting",
    "guide": "1, 小朋友，你所在城市开始实行垃圾分类了吗？你知道垃圾应该怎样分类吗？2. 遇到不熟悉的单词，记得标注出来哦！",
    "en": "Normally, most people throw rubbish away without classifying. However, in some places, people intend to remove this bad habit. And everyone is required to carry out the rubbish sorting policy instead of littering everywhere. Different rubbish should be treated differently on purpose. Kitchen rubbish is likely to go off in several days, which should be classified from other rubbish and put into a dustbin. Recycled rubbish, such as glass and paper, can be reused, which helps to reduce waste and save resources. Some rubbish that is hard to break down may remain for thousands of years on the earth and spoil the environment. * Rubbish sorting has its benefits, and it is definitely a sensible policy. In some countries, people are active in sorting rubbish. Parents and teachers are strict with children and help them create the awareness of rubbish sorting from an early age. Different rubbish bins are put in a fixed spot for different rubbish in streets and communities. Some communities also organise local people as volunteers to sort rubbish without rewards. All these make more and more people realise the importance of sorting garbage. In my hometown, the environment has improved a lot due to rubbish sorting and recycling. In the past, mountains were bald because trees had been cut down and supplied to factories as raw materials for paper. But now, paper is recycled. There is a decline in the amount of wood usage. People can rest in the shade of dense trees. Regarding rubbish sorting 5 some people still lack experience. However, as long as they suppo the policy and keep environmental protection in their mind to make the damage of rubbish to our environment, they can hopefully gain unexpected results. Although it is hard to make a huge difference at once, at least we can protect our environment step by step.",
    "cn": "通常，大多数人扔垃圾的时候不进行分类。但是，在某些地方，人们打算改掉这种坏习惯。人人都必须执行垃圾分类政策，禁止乱扔垃圾。不同的垃圾应该有目的地区别对待。厨余垃圾可能会在几天内变质，应该与其他垃圾分开扔进垃圾桶；玻璃和纸之类的可回收垃圾可以循环使用，这有助于减少浪费、节省资源。一些难以降解的垃圾可能会在地球上留存数千年，破坏环境。垃圾分类有其好处，且绝对是明智之举。在某些国家，人们正在积极地执行垃圾分类。父母和老师们对孩子们严格要求，帮助他们从小创建垃圾分类意识。在道路旁、社区里，不同类型的垃圾箱放置在固定的位置以容纳不同种类的垃圾。一些社区还组织本区居民作为志愿者，无偿帮助垃圾分类。所有这些使越来越多的人意识到了垃圾分类的重要性。在我的家乡，由于垃圾分类和回收，环境已经得到了很大的改善。在过去，人们为了给工厂提供造纸的原材料大量砍伐树木。但是如今人们对废纸进行回收利用，砍伐的木材量大大减少。人们可以在茂密的树荫下休息。关于垃圾分类，有些人仍然缺乏经验。但是，只要他们支持这项政策并将环境保护牢记于心，把垃圾对环境的破坏降到最低，他们就有希望取得意想不到的结果。尽管很难一蹴而就，但至少我们可以逐步使环境得到改善。"
  },
  "Day 27": {
    "title": "Communication and Technology",
    "guide": "1. 通信工具的发明让人类的沟通更加便捷，我们一起来了解一下通信工具的发展历程吧！2, 遇到不熟悉的单词时，记得用笔标记出来哦！",
    "en": "The inventions of communication tools made the connection of our world possible. In the past, people had to communicate face to face. It was common that they travelled a long way to meet each other. A hundred years ago, the telephone and fax were invented to make our communication more efficient. People could ring up friends through telephone, and send messages through fax. At that time, some operators were in charge of dialing telephone numbers. After the person on the other side answered the phone, they would transfer the line to the person who dialed. Because telephone lines were limited, when the lines were engaged, they had to wait for a long time, which was time-consuming. The invention of the smartphone solved this problem well. People carried smartphones everywhere, and they could call and reply at once. Gradually, people realised that visual chatting could convey more information than vocal chatting, but the electronic devices at that time couldn't enable people to get access to see each other. Video calls that use webcams were invented later. The computer is another great invention for humans. At first, the computer was of large volume and slow, which was used as a calculator. With the hardware and server updated, the computer became smaller and faster. Nowadays, when switching on this tiny machine, we are able to connect with the large world. We can install software to make a computer have multiple functions. For example, we 该敌事巧记PET核心词汇 can not only surf website home pages by search engines but also chat with relatives or friends far away through social software. Fax gradually disappears from our sight, because data can be sent through the computer easily. Social media is developing rapidly. Take blogs as an example. Bloggers upload video clips to mark their world through the Internet. Advanced technology has both advantages and disadvantages. It brings convenience and efficiency to us, but it also disturbs our pace and speeds our world up. The key is whether we can make good use of technology. < 交流与科技",
    "cn": "通信工具的发明使我们的世界连接成为可能。过去，人们不得不面对面进行交流，为了见上一面走很长一段路是很常见的。100年前，电话和传真机的发明使我们的沟通变得更高效。人们可以给朋友打电话，用传真发送消息。那时，话务员负责拨打电话号码，当电话另一端的线路接通后，他们再将线路转给拨打电话的人。由于电话线路有限，当电话占线时，他们不得不等待很长时间，这样很耗时。智能手机的发明很好地解决了这个问题。智能手机便于携带，人们可以立刻拨打和接听电话。渐渐地，人们意识到视频聊天可以比语音聊天传达更多的信息，但是当时的电子设备无法让人们看到对方。后来，使用摄像头的视频通话便应运而生。计算机是人类的另一项伟大发明。起初，计算机体积庞大、速度缓慢，被用作计算器。随着硬件和服务器的不断更新，计算机变得越来越小、越来越快。如今，打开这台小巧的机器后，我们可以与偌大的世界相连。我们可以通过安装软件来使计算机具备多种功能。例如，我们不仅可以通过搜索引擎浏览网站主页，还可以通过社交软件与远方的亲戚朋友聊天。传真逐渐从我们的视野中消失了，因为数据可以通过计算机轻松发送。社交媒体快速发展。以博客为例，博主们通过互联网上传视频短片来记录自己的生活。先进的技术有利也有弊，在为我们带来便利和效率的同时，也扰乱了我们的步调，让世界加速运转。关键在于我们是否可以让先进技术为我们所用。"
  },
  "Day 28": {
    "title": "Robots",
    "guide": "1, 小朋友，你喜欢机器人吗？机器人在我们的生活中都有哪些用途呢？2. —起找出文中提到的几种机器人及其用途吧！",
    "en": "People have an argument over the use of robots. After heated discussions, it is advised to give up robots by some experts. Their explanations are that robots may replace humans one day and increase unemployment rates. It is hard to accept unemployment for some workers, but in the long run, people are freed from simple and boring work and are likely to have more opportunities to do what brings them great pleasure. On the other hand, some people disagree with this opinion because they think the advantages of robots weigh more than the disadvantages. The reality is that robots are widely used in our life. Nowadays, people are busy and lonely. Robots can be their friends and accompany them. Their relationships rely on mutual trust and they keep in close contact with each other through daily activities. People can tell robots their secrets, and robots can give proper responses on request. They can even tell a joke to help their owners relax when they recognise that they are experiencing something unpleasant. More and more household robots are recommended to ordinary people. Household robots can do housework, such as cleaning the untidy room and even unpacking parcels. They can play music out loudly when the owners want to listen to music. In new industries, robots can be a delivery machine and help to increase the efficiency of goods distribution. More and more people sign up as robot engineers with robot companies. They update robots to recover bugs on a regular basis. More and more people are persuaded of robots' advantages and use them in daily life. The future of robots is not unknowr and will not get us down. People should reasonably develop robots without ignoring their disadvantages. It is unlikely that the development of robots can be interrupted.",
    "cn": "人们对机器人的使用存在争议。经过激烈的讨论后，一些专家建议放弃机器人。他们的解释是，机器人有一天可能会取代人类，增加失业率。失业让有些工人难以接受，但是从长远来看，人们能从简单乏味的工作中解放出来，并可能有更多的机会做带给他们快乐的事情。另一方面，有些人不同意这种观点，因为他们认为机器人对人类来说利大于弊。现实情况是机器人在我们的生活中得到了广泛的应用。如今，人们忙碌而孤独，机器人可以成为他们的朋友并且陪伴他们。人与机器人的关系依靠相互信任，并通过日常活动彼此保持紧密联系。人们可以向机器人倾诉秘密，机器人可以根据人类的要求给出适当的回应，甚至当它们识别出自己的主人不开心时，可以开个玩笑来帮助他们放松。越来越多的家用机器人进入了大众生活。家用机器人可以做家务，例如打扫凌乱的房间，甚至拆包裹。当主人想听音乐时，它们可以大声播放音乐。在新兴工业中，机器人可以送货，提高商品分配效率。越来越多的人与机器人公司签约，成为机器人工程师。他们定期更新机器人以修复错误。越来越多的人相信机器人的优势，并且在生活中使用机器人。机器人的前途并非未知，亦不会让我们失望。人们应该在意识到机器人的缺点后，合理地开发它们。似乎没有什么可以阻碍机器人的发展。"
  }
};
